stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild -scheme MathKit -configuration "Debug" -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty   
    - xcodebuild -scheme MathKit -configuration "Debug" -destination 'platform=macOS,variant=Mac Catalyst' test | xcpretty 
  tags:
    - ArtemsMacbook 